### ISSUE TITLE
How to parse xml tags (was img not working when use a XML tag)

### ISSUE THREAD

**Issue by lucasmpaim** [malcommac/SwiftRichString#100]
**Current behaviour:**
Now, the tag are raw added on text, like:

<img width="375" alt="wrong behaviour" src="https://user-images.githubusercontent.com/7849484/72000314-ca720100-3221-11ea-9ec5-b2fe2ccd0075.png">

**Expected bahaviour:**
The correct bahaviour is change the "img" tag by correct image, like:

<img width="391" alt="Correct behaviour" src="https://user-images.githubusercontent.com/7849484/72000388-f7261880-3221-11ea-8629-69c8bb1ccd60.png">

**Code:**

```swift
"""
- Use maiúsculas e minúsculas <img named="ic_blue_check_filter"/>
"""
            .set(style: Style {
                $0.font = NAVIGATION_FONT.withSize(14)
                $0.color = UIColor(hex: "#8E8E8E")
            })
```

**Comment by malcommac** [comment]
You should use `StyleGroup` (it will be renamed to `StyleXML` into the next version) in order to parse XML tags, including built-in `img` tag.

So for your example:


```swift
    let text = """
                    - Use maiúsculas e minúsculas <img named="therocket"/>
                    """
        
    let baseStyle = Style {
      $0.font = UIFont.boldSystemFont(ofSize: 14)
      $0.color = UIColor(hexString: "#8E8E8E")
    }
    let styleXML = StyleXML(base: baseStyle, [:])
    self.textView?.attributedText = text.set(style: styleXML)
```
