### ISSUE TITLE
StandardXMLAttributesResolver not recognizing links if custom style is provided for "a" tag

### ISSUE THREAD

**Issue by stefanomondino** [malcommac/SwiftRichString#102]
### Scenario: 
we have a `StyleGroup` rendering some very basic html text. We have defined styles for most common tags, including a custom one for `a`. We're also using `href` informations through the `.link` attributed string key to trigger events on a `TTTAttributedLabel`.

### Analysis: 
We expected to find the `.link` attribute populated with the original href, but this doesn't work out of the box:
- If we **DO NOT** include a custom Style for the "a" tag, the link attribute is set to proper href
- if we *DO** include the custom style inside the group, the link is not set.

The root cause seems to be in the `StandardXMLAttributesResolver` implementation: 
- if `a` is present in style's attributes, the `applyDynamicAttributes(...)` method is called. Inside the standard implementation, there's nothing about href default handling: it's taken for granted that it will be the Style to take care of it, but the style doesn't have access to the dynamic value of the href
- if `a` is missing, the `styleForUnknownXMLTag()` is called, properly handling the link.

### Workaround: 
We were able to create a custom resolver by wrapping the standard one like this. 

```swift 
open class MyXMLDynamicAttributesResolver: XMLDynamicAttributesResolver {
    public func styleForUnknownXMLTag(_ tag: String, to attributedString: inout AttributedString, attributes: [String : String]?, fromStyle: StyleXML) {
        wrapper.styleForUnknownXMLTag(tag, to: &attributedString, attributes: attributes, fromStyle: fromStyle)
    }
    let wrapper: XMLDynamicAttributesResolver
    init(_ wrapper: XMLDynamicAttributesResolver) {
        self.wrapper = wrapper
    }
    public func applyDynamicAttributes(to attributedString: inout AttributedString, xmlStyle: XMLDynamicStyle, fromStyle: StyleXML) {
        if xmlStyle.tag == "a" {
            self.styleForUnknownXMLTag("a", to: &attributedString, attributes: xmlStyle.xmlAttributes, fromStyle: fromStyle)
        }
        wrapper.applyDynamicAttributes(to: &attributedString, xmlStyle: xmlStyle, fromStyle: fromStyle)
    }
}
```

and by setting it like this in our group:
```swift
 let group = StyleGroup(base: myBaseStyle, ["a": heavy.byAdding {
                $0.color = Color.black
                $0.minimumLineHeight = 24.0
                $0.size = 14.0
                $0.underline = (.thick, Color.black)
            }])
            group.xmlAttributesResolver = MyXMLDynamicAttributesResolver(group.xmlAttributesResolver)
```

## Proposed solutions:
1) inside the `StandardXMLAttributesResolver`, fallback to the default implementation for `a` tags
2) make `StandardXMLAttributesResolver` methods (and initializer!) `open` and not internal/public (that's why we had to wrap the resolver inside another class instead of subclassing it)

I can quickly  put together a pull request if needed but I'd like to know which is the intended behavior 

Ciao :)

**Comment by malcommac** [comment]
Absolutely right, we have discovered this issue few days ago. If you want to make a PR for both of the points I'll be happy to merge it. Thanks!

**Comment by stefanomondino** [comment]
I'm on it :)
