### ISSUE TITLE
Example app crash when running on Xcode version 11.2.1

### ISSUE THREAD

**Issue by zulfiker** [malcommac/SwiftRichString#106]
When trying to run the exapleiOs app from xcode target, the app crash . 

<img width="1280" alt="Screen Shot 2020-01-27 at 3 45 31 PM" src="https://user-images.githubusercontent.com/2470977/73164588-6fdf0d00-411c-11ea-8500-b1b0bed8a373.png">

**Comment by malcommac** [comment]
Checkout the newest 3.7.1 published several minutes ago. Should fix this issue.

**Comment by zulfiker** [comment]
just checked . it is woking fine after latest pull . thanks
