### ISSUE TITLE
Possible to go from NSAttributedString, to "simple" tags?

### ISSUE THREAD

**Issue by smhk** [malcommac/SwiftRichString#11]
In this great library, it's unclear:

Say I have an attributed string, which has (let's say) ONLY bold and italic sections.

I want to PRODUCE THIS OUTPUT:

`This string <b>has</b> only some <i>bold and some</i> italic.`

As you know, you can certainly generate html using Apple's built-in generator, but it produces wildly complex CSS output (see below for example).

So, I know that with SwiftRichString you can go FROM  something like 

`This string <b>has</b> only some <i>bold and some</i> italic.`

to an NSAttributedString - but can you go in the other direction???

Sorry it's a bit unclear from the doco - or maybe I'm just lame  :)

Example of Apple's crappy full-css output...,

if you use `.attributedText.data`

```
><!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="Content-Style-Type" content="text/css">
<title></title>
<meta name="Generator" content="Cocoa HTML Writer">
<style type="text/css">
p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Open Sans'}
span.s1 {font-family: 'Open Sans'; font-weight: normal; font-style: normal; font-size: 14.00pt}
span.s2 {font-family: 'OpenSans-SemiboldItalic'; font-weight: bold; font-style: italic; font-size: 14.00pt}
</style>
</head>
<body>
<p class="p1"><span class="s1">So, </span><span class="s2">Apple made</span><span class="s1"> this stuff OK</span></p>
</body>
</html>
<
```

**Comment by malcommac** [comment]
Hi,
No, currently the transformation from attributed string to html-tag-like version is not supported and it's not in the scope of the library.
I'll evaluate it but frankly it's not a priority for the library.
If you want, I'll be happy to accept a PR for it.
