### ISSUE TITLE
Xcode 9 (beta) compile error: Cannot express tuple conversion '(Int?, Element?)' to '(index: Int?, item: Style?)'

### ISSUE THREAD

**Issue by MartijnvdV** [malcommac/SwiftRichString#13]
A compile error occurs when compiling with Xcode 9 (beta) using SwiftRichString (0.9.8). 
When having swift compiler version set to "Swift 3.2" I get the following error in file Extention.swift line 78:

_Cannot express tuple conversion '(Int?, Element?)' to '(index: Int?, item: Style?)'_

**Comment by nikans** [comment]
Please merge this

**Comment by MartijnvdV** [comment]
Please fix the merge conflict and merge the fix.

**Comment by alec-c4** [comment]
@malcommac could you merge PR?

**Comment by piv199** [comment]
@malcommac xcode 9 is out and this bug is still here :(

**Comment by malcommac** [comment]
@piv199 is your a Swift 3.x project? Are you using `pod 'SwiftRichString', '~> 0.9.10'`? Or is it a Swift 4 project?

**Comment by piv199** [comment]
@malcommac I'm sorry, yeah I haven't updated the pod, now it works.

**Comment by highthem** [comment]
not working with swift 4 :( 
`Cannot convert value of type '[NSAttributedStringKey : Any]' (aka 'Dictionary<NSString, Any>') to exp`

**Comment by piv199** [comment]
@highthem which version do you use, setting swift 4 on latest version works

**Comment by highthem** [comment]
@piv199 I went back to swift 3 as many of my dependecies did not support swift 4 yet and got this error on SwiftRichString

<img width="1063" alt="screen shot 2017-09-25 at 14 21 36" src="https://user-images.githubusercontent.com/2728100/30808135-1f8e4f8e-a1fd-11e7-8f86-3f126c1ab135.png">

**Comment by piv199** [comment]
@highthem, you are not using the latest version, xcode 9 allows to mix swift 3.2 and 4 targets...

**Comment by highthem** [comment]
@piv199 how to do that?

**Comment by highthem** [comment]
@piv199 thank you :)

**Comment by piv199** [comment]
you could try to use `pod update`
And than set in pod file or in build settings SwiftRichString swift version to `swift 4.0`

**Comment by robcecil** [comment]
I've submitted a bug report to the carthage tracker.

[#2270](https://github.com/Carthage/Carthage/issues/2270)

**Comment by malcommac** [comment]
fixed in swift 4 version
