### ISSUE TITLE
When applying StokeAttribute color becomes transparent

### ISSUE THREAD

**Issue by ignotusverum** [malcommac/SwiftRichString#14]
Using following code:

```
let titleStyle = Style("title", {
            $0.font = FontAttribute(font: .WorkSansExtraBold(17))
            $0.align = .center
            $0.color = UIColor.white
            $0.stroke = StrokeAttribute(color: UIColor.black, width: 1)
            $0.kern = 2
        })
```

And text color becomes transparent. Any ideas why ?

Thanks !

**Comment by malcommac** [comment]
Hi @ignotusverum; according to the documentation `StrokeAttribute`'s `width` value is interpreted as a percentage of font point size and it controls the text drawing mode: positive values effect drawing with stroke only; negative values are for stroke and fill.

So, just to follow your example, you should try to put a negative value:

```swift
let titleStyle = Style("title", {
	$0.font = FontAttribute(font: UIFont.systemFont(ofSize: 30))
	$0.align = .center
	$0.stroke = StrokeAttribute(color: UIColor.black, width: -3)
	$0.color = UIColor.red
	$0.kern = 2
})
let string = try! MarkupString(source: "HELLO <title>WORLD</title>", styles: [titleStyle]).render()
```

Will show:

<img width="164" alt="screen shot 2017-07-06 at 23 18 15" src="https://user-images.githubusercontent.com/235645/27933383-79073dfa-62a1-11e7-9070-fa8c3c358305.png">
