### ISSUE TITLE
Compile issue with Xcode 9 Beta

### ISSUE THREAD

**Issue by jgarciatt** [malcommac/SwiftRichString#15]
Im getting this error when trying to compile the project using Carthage pointing out to the beta version of Xcode:

*** Building scheme "SwiftRichString" in SwiftRichString.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/jgarcia/Developer/music-mobile-ios-v3/Carthage/Checkouts/SwiftRichString/SwiftRichString.xcworkspace -scheme SwiftRichString -configuration Release -derivedDataPath /Users/jgarcia/Library/Caches/org.carthage.CarthageKit/DerivedData/SwiftRichString/0.9.8 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/5y/6n4_nl4x40qg1z_6n8d_z9xc0000gp/T/carthage-xcodebuild.pNKVla.log

Any suggestion of what should I do.

Thanks.

**Comment by unnamedd** [comment]
@jgarciatt take a look at this issue https://github.com/malcommac/SwiftRichString/issues/13, this is the problem, without any solution fixing it yet :(
