### ISSUE TITLE
I Decided to try out you pod there are a few issues when converting Im using latest of Xcode and swift 3.0

### ISSUE THREAD

**Issue by pprevalon** [malcommac/SwiftRichString#2]
I Decided to try out you pod there are a few issues when converting Im using latest of Xcode and swift 3.0
![screen shot 2016-12-31 at 9 18 28 pm](https://cloud.githubusercontent.com/assets/19171619/21579975/e88d2ca2-cf9e-11e6-87f7-0ad228bc3992.png)

**Comment by malcommac** [comment]
Resolved in 0.9.9
