### ISSUE TITLE
Set UITextView.typingAttributes (and extract attributes dict from Style instance)

### ISSUE THREAD

**Issue by charlesbevans** [malcommac/SwiftRichString#23]
I believe UITextView.typingAttributes contains the "default" style for UITextView. I'd like to be able to set it with the styles I'm using in the attributed text.
(I'm having an issue with getting a default font to be registered for an empty UITextView that will be edited.)

**Comment by malcommac** [comment]
Hi @charlesbevans , just extract the attributes dictionary from the `Style` instance using `. attributes` property.
