### ISSUE TITLE
Malloc issue leads to crash for a mixed Swift version implementation

### ISSUE THREAD

**Issue by scottcarter** [malcommac/SwiftRichString#28]
I have discovered a crash scenario in the following situation:

* Release Configuration
* Project compiled with Swift 3.2
* SwiftRichString compiled with Swift 4.0 (using SwiftRichString version 1.0.1)
* macOS project (could also be present in iOS - not tested)
* macOS Sierra version 10.12.6
* Xcode version 9.2

I have created a simple macOS project that reliably reproduces the issue:
https://github.com/scottcarter/SwiftRichString_MallocBug

I found that if any of the first three criteria is changed, the problem goes away.  I.e. if a Debug configuration is used, if the project is compiled with Swift 4.0, or I compile SwiftRichString with Swift 3.2 (using SwiftRichString version 0.9.10).

**Comment by dskibin** [comment]
I have same as well

**Comment by malcommac** [comment]
You should use 1.x for Swift 3 branch
