### ISSUE TITLE
commented-out example code obsolete?

### ISSUE THREAD

**Issue by abumami** [malcommac/SwiftRichString#3]
The file ViewController.swift in the DemoApp folder has the following code in lines 64-66:

```
//	let sourceURL = URL(fileURLWithPath: "...")
//	let sourceText = RichString(sourceURL, encoding: .utf8, [bold,italic])!
//	let renderedText = sourceText.text
```

The method RichString() doesn't seem to exist anywhere. Is there a replacement function? Or is it hiding from me?

**Comment by malcommac** [comment]
I've removed it from the final version because I would to keep only the core of the library, so download/read of a file should be done outside.

**Comment by abumami** [comment]
Thanks. I already played around loading files myself. I just thought that maybe there were some things that I missed.
