### ISSUE TITLE
Support for Dynamic Text Size of iOS11

### ISSUE THREAD

**Issue by iOSUser110** [malcommac/SwiftRichString#32]
Can you provide feature of dynamic text size , with font , which introduced in iOS 11
https://developer.apple.com/videos/play/wwdc2017/245/

**Comment by AntoineDuval** [comment]
Do you have any plan to support dynamic text (UIFontMetrics) ?

Thanks !

**Comment by fabiosoft** [comment]
Please support dynamic font 🥇
