### ISSUE TITLE
Fixed font/size attributes which are not inherited correctly 

### ISSUE THREAD

**Issue by xdxavier** [malcommac/SwiftRichString#37]
add method will override all existing attributes.

```swift
let styleA = Style {
	$0.color = UIColor.white
	$0.size = 24
}

let styleB = Style {
	$0.color = UIColor.white
	$0.size = 14
}

let styleC = Style {
	$0.color = UIColor.red
}

let a = "hello".set(style: styleA)
let b = "world!".set(style: styleB)
let ab = (a + b).add(style: styleC)
```

the expected result of ab should keep different font size and append red color. But real result is reset font size and append red color.

p.s. version 2.0.1

**Comment by malcommac** [comment]
Fixed.
Now `font` and `size` are correctly inherited when not specified in a `StyleProtocol` instance. By setting `font` you are also setting its size; by passing `size` only SwiftRichString attempts to enumerate between the fonts of the attributed string by altering it along with the (optional) unique font attributes you have set.

The result of the code above is:
<img width="105" alt="screen shot 2018-09-03 at 17 01 33" src="https://user-images.githubusercontent.com/235645/44993739-e0bbdd00-af9b-11e8-92d3-2eda490c732d.png">
