### ISSUE TITLE
Dynamic value support for TagAttributes (ie. apply link value from an 'a'/'href' tag)

### ISSUE THREAD

**Issue by jdanthinne** [malcommac/SwiftRichString#45]
When trying to convert HTML to attributedText with this wonderful tool, the only thing I'm missing is a way to construct the `linkURL` with the content of a tag attribute.

I've looked into your code and here's an idea: instead of taking an optional URL for the Style `linkURL` property, what about a "`URLConvertible`" type?

Here's a draft of what it could look like, but I don't understand your parsing process (yet) to be able to fully implement it.
```swift
//MARK: - URLConvertible

/// An enumeration representing the source of the URL to be applied.
///
/// - url: URL type.
/// - string: String url.
/// - tagAttribute: value of attribute from a parsed tag (ie: "href").
/// - tagText: text content from a parsed tag.
public enum URLConvertible {
    case url(URL)
    case string(String)
    case tagAttribute(String)
    case tagText
    
    func url(for tag: StyleGroup.TagAttribute?) -> URL? {
        switch self {
        case .url(let url):
            return url
        case .string(let string):
            return URL(string: string)
        case .tagAttribute(let attribute):
            return URL(string: tag.attributes[attribute])
        case .tagText:
            return URL(string: tag.content)
        }
    }
    
}
```
We could then just do the following:
```swift
attrString.add(style: StyleGroup(["a" : Style {
    $0.linkURL = .tagAttribute("href")
}]))
```

**Comment by WHeB** [comment]
How to click the link to jump to a new controller？

**Comment by jdanthinne** [comment]
@WHeB Use the Data Detectors of UITextView (or use the [delegate method](https://developer.apple.com/documentation/uikit/uitextviewdelegate/1649337-textview)).
