### ISSUE TITLE
Fixed an issue with Style copying via `byAdding()` function

### ISSUE THREAD

**Issue by tuxfamily** [malcommac/SwiftRichString#47]
Hello.

I would like to report/highlight the breaking changes of the latest versions.

With this simple group declaration

```swift
typealias MainFont = Font.HelveticaNeue

enum Font {
    enum HelveticaNeue: String {
        case light = "Light"
        case bold = "Bold"
        case boldItalic = "BoldItalic"
        func with(size: CGFloat) -> UIFont {
            return UIFont(name: "HelveticaNeue-\(rawValue)", size: size)!
        }
    }
}

let normal = Style {
    $0.font = MainFont.light.with(size: 16)
}

let bold = normal.byAdding {
    $0.font = MainFont.bold.with(size: 16)
}

let bold_italic = normal.byAdding {
    $0.font = MainFont.boldItalic.with(size: 15)
}

let stylesDefs = [
    "bold": bold,
    "bold_italic": bold_italic,
]

let defaultStyles = StyleGroup(base: normal, stylesDefs)
```

And the following text:

```swift
var text = "This search engine is specifically designed to solve <bold>crosswords</bold> or <bold>arrowords puzzles</bold>.\n\nIn order to solve a word, you can either enter its <bold>definition</bold> or its <bold>pattern</bold>.\n\n<bold_italic>For patterns, you can simply press the spacebar for each unknown letter.</bold_italic>"
text.set(style: defaultStyles)
```

The output with version 2.0.1 is as expected:

![swiftrichstring-2 0 1](https://user-images.githubusercontent.com/3294174/45351046-87643700-b5b5-11e8-9d09-3f929b260df5.png)

With version 2.0.2 I've this:

![swiftrichstring-2 0 2](https://user-images.githubusercontent.com/3294174/45351047-87643700-b5b5-11e8-8d66-c9b5c0355910.png)

With version 2.0.3, this:

![swiftrichstring-2 0 3](https://user-images.githubusercontent.com/3294174/45351049-87643700-b5b5-11e8-8f48-7bc148aa6f40.png)

And the latest 2.0.4 is the worst:

![swiftrichstring-2 0 4](https://user-images.githubusercontent.com/3294174/45351050-87fccd80-b5b5-11e8-9419-f7e0e48306ab.png)

I've tried to use your new declaration style

```swift
let normal = Style {
    $0.font = SystemFonts.HelveticaNeue_Light.font(size: 16)
}

let bold = Style {
    $0.font = SystemFonts.HelveticaNeue_Bold.font(size: 16)
}

let bold_italic = Style {
    $0.font = SystemFonts.HelveticaNeue_BoldItalic.font(size: 15)
}
```

But it does not solve the issue, I keep getting the output of the last screenshot.

So either it's a breaking change or it's a bug, but for now, I will force the use of version 2.0.1 as it is the only one who gives the expected output.

**Comment by BrettJackson1987** [comment]
I'm getting this same bug. The only way I'm able to use this library is when I make a new style for every tag I want to use. Highly inefficient.

From what I have seen, it appears that "byAdding" is not actually copying or cloning the style, but is instead modifying the original. The code above shows this as it is just stacking up all the styles or merely using the last modification, which is the bold italic.

I can post my code too, but it is not too dissimilar from that above.
