### ISSUE TITLE
How can we apply multiple styles to same string using regex pattern?

### ISSUE THREAD

**Issue by hardik99** [malcommac/SwiftRichString#5]
Hi,

I am facing issue in applying multiple styles in textview text. If text contains email regex then it is in different style. If it is contains any numbers than numbers will also display in different style.

So how can I achieve that using this?

**Comment by malcommac** [comment]
Hi,
With 0.9.9 I've introduced a new function to `String` instances called `func set(regExpStyles: [RegExpPatternStyles], default dStyle: Style? = nil) -> NSMutableAttributedString`.
This function accepts:
* an array of `RegExpPatternStyles` objects. A single `RegExpPatternStyles` is a struct which defines a regular expression and an array of `Style`s to apply when found.
* a default `Style`: optional, if specified this style is applied before any other regular expression, to the entire string.

Following your request we can, for example, define two regular expression to search email and urls in a string:
```swift
let regexp_url = "http?://([-\\w\\.]+)+(:\\d+)?(/([\\w/_\\.]*(\\?\\S+)?)?)?"
let regexp_email = "([A-Za-z0-9_\\-\\.\\+])+\\@([A-Za-z0-9_\\-\\.])+\\.([A-Za-z]+)"
```

and defines two styles to apply when matches:
```swift
let style_email = RegExpPatternStyles(pattern: regexp_email) {
	$0.color = .red
}!
		
let style_url = RegExpPatternStyles(pattern: regexp_url) {
	$0.color = .blue
}!
```

Then:
```swift
let text_example = "My email is hello@danielemargutti.com and my website is http://www.danielemargutti.com"
var result = text_example.set(regExpStyles: [style_email, style_url])
```

Will produce this:

<img width="350" alt="screen shot 2017-07-07 at 00 14 07" src="https://user-images.githubusercontent.com/235645/27935097-38597a40-62a9-11e7-9a8d-48edeedcee4e.png">

0.9.9 will be released soon.
Thank you for your suggestion.
Have a nice day.

**Comment by hardik99** [comment]
Happy to see this.

Thanks
