### ISSUE TITLE
Render HTML text

### ISSUE THREAD

**Issue by Momeks** [malcommac/SwiftRichString#62]
Hello, Thank you for this cool framework!. I just need to display an HTML code using this. But when I run the app, my label shows nothing!.

here is my code:
```
 let file = Bundle.main.path(forResource: "html", ofType: "txt")!
        do {
            htmlBody = try String(contentsOfFile: file, encoding: .utf8)
        } catch let error {
            print(error)
        }

        label.attributedText = htmlBody.set(style: "str")
```
my txt file has all tags and styles so I don't need it to create style group.
How can I fix this?

**Comment by malcommac** [comment]
You need to associate style to each used tag entity, they are not really html tag rendered by a html rendered as like `NSAttributedString` functions. You should use native html loader from `NSAttributedString`.
