### ISSUE TITLE
Changing Style with TAG based sttrings

### ISSUE THREAD

**Issue by flescio** [malcommac/SwiftRichString#72]
Hi,

the style on tag based string works very well.

But if I try to change the style once again, the info about the tag on the styledText property is lost.

Works again if I reset the styledText with the original value with tags.

**Comment by stefanomondino** [comment]
Ciao @flescio,
I'm afraid that's how `StyleGroup` works. It scans every tag in the original string, removes them entirely and eventually apply the style informations to the substring matching the original range of the tags.

**Comment by malcommac** [comment]
I've implemented this feature for 3.5.0 along with other nice additions.
See the tag https://github.com/malcommac/SwiftRichString/issues/77.
I'll close this.
