### ISSUE TITLE
linkURL issue with UITextView

### ISSUE THREAD

**Issue by jeremy6462** [malcommac/SwiftRichString#74]
I'm responding to a user tapping a link in a `UITextView` using `UITextView.textView(_:, shouldInteractWith:, in:, interaction:)`. Unfortunately, when using `style.linkURL = .string("someText://")` to set up the attributed text for that text view, `shouldInteractWith` does not fire when the user taps the attributed link. However when I set the style attributes using `NSAttributedString` keys (like so `style.set(attribute: "someText://", forKey: .link)` the `shouldInteractWith` text view delegate fires correctly.

I'd be interested in digging into a fix for this, however before I spent anytime on this, I'd like to check with those more knowledgable about the implementation to see if this is intended behavior.

**Comment by RolandasRazma** [comment]
your class needs to conform to `UITextViewDelegate`. (class MyVc: UITextViewDelegate {})
Simply adding method is not enough

**Comment by jeremy6462** [comment]
I have added conformance to `UITextViewDelegate`. I've included a sample project to reproduce the issue below, along with the important excerpt of the code [SRS Link URL Bug.zip](https://github.com/malcommac/SwiftRichString/files/3593064/SRS.Link.URL.Bug.zip). 

```class ViewController: UIViewController {

    let textView = { () -> UITextView in
        
        let style = Style {
            $0.backColor = UIColor.blue
            $0.linkURL = URLRepresentable.string("test://")
        }
        
        let textView = UITextView(frame: .zero)
        textView.isEditable = false
        textView.isSelectable = true
        textView.attributedText = "Test".set(style: style)
        textView.translatesAutoresizingMaskIntoConstraints = false
        return textView
        
    }()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.textView.delegate = self
        self.view.addSubview(textView)
        NSLayoutConstraint.activate([
            textView.centerXAnchor.constraint(equalTo: self.view.centerXAnchor),
            textView.centerYAnchor.constraint(equalTo: self.view.centerYAnchor),
            textView.widthAnchor.constraint(equalToConstant: 100),
            textView.heightAnchor.constraint(equalToConstant: 100),
            ])
    }

}

extension ViewController: UITextViewDelegate {
    
    func textView(_ textView: UITextView, shouldInteractWith URL: URL, in characterRange: NSRange, interaction: UITextItemInteraction) -> Bool {
        print("Not Fired")
        return true
    }
    
}```

**Comment by RolandasRazma** [comment]
interestingly enough if you replace your `textView.attributedText = ` with `textView.attributedText = "<a>Test</a>".set(style: StyleGroup(["a": style]))` it does work

**Comment by RolandasRazma** [comment]
with your example it generates `{ NSLink = "SwiftRichString.URLRepresentable.url(test://)"; }` with is clearly invalid link. So I guess the questions is: are you using Lin correctly or is it a bug :)

**Comment by jeremy6462** [comment]
I misunderstood how to use `linkURL`, so I'll close this

**Comment by zhangferry** [comment]
I had the same problem. When use `style.linkURL = URLRepresentable.string("url")`, I can't get tap event. However when I set the style attributes using NSAttributedString keys (like so style.set(attribute: "url", forKey: .link) the shouldInteractWith text view delegate fires correctly. 

The url is correct and can be access.

**Comment by malcommac** [comment]
Have you tried the new version? Also take a look at the demo application, it contains an example of tappable url.

**Comment by zhangferry** [comment]
@malcommac I'm sorry for the late reply. Everything worked fine in the latest release, thank you so much for writing such a useful library, which I've used on several projects.
