### ISSUE TITLE
Strip away xml tags when no style is matching tag

### ISSUE THREAD

**Issue by stefanomondino** [malcommac/SwiftRichString#79]
When custom XML string is converted to an attributed string with a `StyleGroup`, the xml tags are not stripped away if a matching style has been configured for the same tag.

I believe it's pointless to leave all those tags in the final string and show them to the final user: if I'm using a `StyleGroup`, it should be implicit that I'm using tags to define inner style.

We could either define a new property for StyleGroup (a `Bool` value defining whether strip xml or not) or, simply, strip away XML when inner style is not found.

Pull request on it's way :)

**Comment by stefanomondino** [comment]
#80 resolves it "naively".

**Comment by malcommac** [comment]
Merged in 3.0.1
