### ISSUE TITLE
Paragraph style not functioning

### ISSUE THREAD

**Issue by lscheepers** [malcommac/SwiftRichString#83]
Good Day,
I have looked through the documentation and the example apps and can not get the paragraphSpacingBefore to work in a UILabel.

I have the following style defined:

        let li = Style {
            $0.paragraphSpacingBefore = textStyle.font.lineHeight / 2
            $0.firstLineHeadIndent = textStyle.font.lineHeight
            $0.headIndent = textStyle.font.lineHeight * 1.71
        }

But the list is displayed on the same line as the rest of the text and not on a new line.

I am using the latest 3.0.1 release

**Comment by malcommac** [comment]
It seems you're trying to use the font property of your UI control (textStyle I suppose) inside the style, but probably it's not the same of the font inside the `li` style.
I've tried with this code where the font is defined externally as reference and it seems works fine.

```swift
let usedFont = UIFont.boldSystemFont(ofSize: 15)
let headerStyle = Style {
            $0.font = usedFont
            $0.paragraphSpacingBefore = usedFont.lineHeight / 2
            $0.firstLineHeadIndent = usedFont.lineHeight
            $0.headIndent = usedFont.lineHeight * 1.71
}
```
