### ISSUE TITLE
iOS 13 - Setting the font property of a style always results in Times New Roman being used

### ISSUE THREAD

**Issue by LisaGonaus** [malcommac/SwiftRichString#84]
**Environment**
* Xcode 11 Beta 5
* iPhone XS (iOS 13 Beta)

**Example**

When the following code is compiled with Xcode 11 and run on iOS 13 any styles that contain fonts stop working correctly.

```
let text = "No issues here, <b>but this text is Times New Roman instead of the heavy system font</b>"

            
let baseStyle = Style { $0.color = UIColor.green }
let heavyFontStyle = Style { $0.font = UIFont.systemFont(ofSize: 14, weight: .heavy) }
            
let styleGroup = StyleGroup(base: baseStyle, [ "b": heavyFontStyle ])
            
let attributedText = text.set(style: styleGroup)

```

![Screenshot 2019-08-08 at 13 33 09](https://user-images.githubusercontent.com/17741112/62700052-346f4b80-b9e1-11e9-975b-efd74ac10c7f.png)

**Comment by wberger** [comment]
I have debugged into this, and I think I know why this happens. Let's assume, we have set the style to SystemFont, Size 14.

**SwiftRichString Font Instantiation on iOS 12 SDK:**
```
FontData.swift, Line 155, attributes(currentFont:, size:) -> [NSAttributedString.Key:Any]
FontConvertible.swift, Line 65, font(size:) -> Font
(lldb) po self
<UICTFont: 0x7fb74dd77f30> font-family: ".SFUIText"; font-weight: normal; font-style: normal; font-size: 14.00pt
(lldb) po self.fontName
".SFUIText"

FontData.swift, Line 159, attributes(currentFont:, size:) -> [NSAttributedString.Key:Any]
po finalFont
<UICTFont: 0x7fb74dc1ced0> font-family: ".SFUIText"; font-weight: normal; font-style: normal; font-size: 14.00pt
```
--> the font name is reported as ".SFUIText" and SwiftRichString is able to instantiate the matching UIFont from this name via `Font(name: self.fontName, size: (size ?? Font.systemFontSize))!`


**SwiftRichString Font Instantiation on iOS 13 SDK:**
```
FontData.swift, Line 155, attributes(currentFont:, size:) -> [NSAttributedString.Key:Any]
FontConvertible.swift, Line 65, font(size:) -> Font
(lldb) po self
<UICTFont: 0x7fa576769f90> font-family: ".SFUI-Regular"; font-weight: normal; font-style: normal; font-size: 14.00pt
(lldb) po self.fontName
".SFUI-Regular"

FontData.swift, Line 159, attributes(currentFont:, size:) -> [NSAttributedString.Key:Any]
po finalFont
<UICTFont: 0x7fa576400020> font-family: "Times New Roman"; font-weight: normal; font-style: normal; font-size: 14.00pt
```
--> the font name is reported as ".SFUI-Regular" and SwiftRichString is NOT able to instantiate a matching UIFont from this name via `Font(name: self.fontName, size: (size ?? Font.systemFontSize))!`. Instead UIFont(name:, size:) seems to fall back to Times New Roman.

**Comment by wberger** [comment]
Here is the according rdar bug report:
https://openradar.appspot.com/6153065

One could apply a workaround by checking for the ".SFUI" prefix in the font names and implementing a special kind of instantiation in these cases. But actually I hope that this gets fixed on Apple's side.

**Comment by wberger** [comment]
I created a pull request containing the workaround: https://github.com/malcommac/SwiftRichString/pull/85

**Comment by malcommac** [comment]
Merged and on track for 3.0.2. Thanks for PR.

**Comment by danqing** [comment]
Now that iOS 13 has been released, can this PR land in master (and have 3.0.2)?

**Comment by 0xacdc** [comment]
Any progress with solving this issue in the Master ? Thx

**Comment by malcommac** [comment]
released

**Comment by danqing** [comment]
Somehow I'm still experiencing the issue with 3.0.2. Am I alone?

**Comment by jdanthinne** [comment]
@danqing Not alone, experiencing this issue as well with 3.0.2.

**Comment by ftsz** [comment]
@danqing Same here. Release 3.0.2 didn't fix the issue on iOS 13 for me.

**Comment by 0xacdc** [comment]
@danqing Same here for 3.0.2 on iOS 13

**Comment by wberger** [comment]
Commit e5c147f280d0ce0f85929e0101f9eb6ff5ccd41f seems to have introduced the issue as there seems to be a mixup with the platform checks. As far as I can see the workaround is now applied to macOS instead of iOS

**Comment by danqing** [comment]
Good catch @wberger. That seems to be the issue. Sending in a PR now.
