### ISSUE TITLE
Link Foreground color not changing.

### ISSUE THREAD

**Issue by sureshmopidevi** [malcommac/SwiftRichString#87]
I have tried this code for changing `foreground` colour of link. but its not working. I tried out `backColor`, thats working fine. Am i missing something here?
```swift
let link = Style {
            $0.color = UIColor.green
            $0.linkURL = URLRepresentable.tagAttribute("href")
            $0.font = UIFont.systemFont(ofSize: TempStorage.getTextSize())
        }

        let group = StyleGroup(base: textStyle, ["a": link])
```
The Color of `Link` remains blue. Any suggestion. Thanks!

**Comment by malcommac** [comment]
Did you close it because it works?
