### ISSUE TITLE
Weird Crash on String.substring(from:length:)

### ISSUE THREAD

**Issue by robertodias180** [malcommac/SwiftRichString#89]
I am having a weird crash on  `String.substring(from:length:)`

`*** -[NSBigMutableString characterAtIndex:]: Index 513 out of bounds; string length 513`
`String.substring(from:length:) + 69`

but this is only happening on some versions of iOS12 (12.4.2, 12.4.1, 12.3.1)
and I can't reproduce this on the simulator 😅

anyone had this issue before?

**Comment by malcommac** [comment]
Can you provide a simple test project so I'll try to reproduce it in my test devices. Thanks

**Comment by malcommac** [comment]
currently marked as invalid due to missing info.
