### ISSUE TITLE
apply defaults to document

### ISSUE THREAD

**Issue by abumami** [malcommac/SwiftRichString#9]
It would be nice if there was an easy way to apply defaults to the document. For example: define a document as default right-to-left, define a document with a default font (family, size, etc), define a document with a theme (background color, text color, etc).

All in all, a very nice project. I'm enjoying playing with it.

**Comment by malcommac** [comment]
You can define a default style; it's the `Style.default` constructor of the `Style` class.
In a sequence of styles it will be applied in first place.

Let me show to you an example:

```swift
let default_style = Style.default {
	$0.font = FontAttribute(.GillSans_Italic, size: 20)
}

let boldred_style = Style("mystyle") {
	$0.color = .red
	$0.font = FontAttribute(.AppleSDGothicNeo_Bold, size: 40)
}
		
let str = "Default style is applied in first place, <mystyle>other styles follows</mystyle>. It's cool!"
let rendered = try! MarkupString(source: str, styles: [default_style,boldred_style]).render()
```

Will produce this:
<img width="380" alt="screen shot 2017-07-06 at 23 26 50" src="https://user-images.githubusercontent.com/235645/27933674-a97e2f88-62a2-11e7-9b2d-85e250a0334d.png">
