### ISSUE TITLE
`numberSpacing` attribute is not applied at all when FontData is produced

### ISSUE THREAD

**Issue by letko-dmitry** [malcommac/SwiftRichString#90]
Looks like it is not added to the list of attributes in the function named `func attributes(currentFont: FontConvertible?, size currentSize: CGFloat?) -> [NSAttributedString.Key:Any]`

**Comment by malcommac** [comment]
Can you provide a live example to test? Thanks

**Comment by malcommac** [comment]
Fixed. thanks
